<?php

class SQLQuery{

   	public static $RECRUITER_FIND_BY_PRIMARY_KEY = "SELECT RECRUITER_ID, FIRSTNAME, LASTNAME FROM RECRUITER WHERE RECRUITER_ID=?";
   	public static $RECRUITER_FIND_BY_LINKEDIN_KEY = "SELECT RECRUITER_ID, FIRSTNAME, LASTNAME FROM RECRUITER WHERE LINKEDIN_ID=?";
   	public static $RECRUITER_INSERT_RECRUITER = "INSERT INTO RECRUITER (LINKEDIN_ID, FIRSTNAME, LASTNAME) VALUES (?, ?,?)";


	public static $JOB_FIND_BY_LINKEDIN_JOB_ID = "SELECT JOB_ID, RECRUITER_ID, COMPANY_ID, LINKEDIN_JOB_ID, TITLE,INTERVIEW_ID, INTERVIEW_URL, LOCATION, DESCRIPTION, IS_ACTIVE, POSTING_DATE, EXPIRATION_DATE,POSTED_BY_LINKEDIN_ID FROM JOB WHERE LINKEDIN_JOB_ID = ?";
    public static $JOB_FIND_BY_RECRUITER_ID = "SELECT JOB_ID, RECRUITER_ID, COMPANY_ID, LINKEDIN_JOB_ID, TITLE,INTERVIEW_ID, INTERVIEW_URL, LOCATION, DESCRIPTION, IS_ACTIVE, POSTING_DATE, EXPIRATION_DATE,POSTED_BY_LINKEDIN_ID FROM JOB WHERE RECRUITER_ID = ?";
    public static $JOB_INSERT_JOB = 'INSERT INTO JOB (RECRUITER_ID,COMPANY_ID,LINKEDIN_JOB_ID,TITLE,ACTIVE,LOCATION,DESCRIPTION,POSTING_DATE,EXPIRATION_DATE,POSTED_BY_LINKEDIN_ID) VALUES (?,?,?,?,?,?,?,?,?,?)';


	public static $INTERVIEW_CREATE_INTERVIEW = 'INSERT INTO INTERVIEW (JOB_ID) VALUES (?)';


	//public static $QUESTION_CREATE_QUESTION = 'INSERT INTO QUESTION (INTERVIEW_ID, STAGE_NO, DESCRIPTION, QUESTION_TYPE, ANSWER_TYPE, ASSESSMENT_CRITERIA, TIME_LIMIT) VALUES (1,1,'What is Java','S','W','Hold of Object Oriented KNowledge',20)';
	public static $QUESTION_CREATE_QUESTION = 'INSERT INTO QUESTION (INTERVIEW_ID, STAGE_NO, DESCRIPTION, QUESTION_TYPE, ANSWER_TYPE, ASSESSMENT_CRITERIA, TIME_LIMIT) VALUES (?,?,?,?,?,?,?)';
	public static $QUESTION_UPDATE_QUESTION = 'UPDATE QUESTION SET DESCRIPTION = ?, ASSESSMENT_CRITERIA = ?,TIME_LIMIT = ? WHERE QUESTION_ID = ?';


	// QUESTION_BANK
	public static $QUESTION_BANK_CREATE = 'INSERT INTO QUESTION_BANK (RECRUITER_ID, QUESTION_ID) VALUES (?,?)';
	public static $QUESTION_BANK_FIND_QUESTIONS_IN_BANK = 'SELECT QUESTION_ID FROM QUESTION_BANK WHERE RECRUITER_ID = ?';


	//INSERT INTO OBJECTIVE_CHOICES (QUESTION_ID, CHOICE_ID,CHOICE_DESCRIPTION,CORRECT_CHOICE) VALUES (1,1,'Its OOO',null)
	public static $OBJECTIVE_CHOICES_CREATE = 'INSERT INTO OBJECTIVE_CHOICES (QUESTION_ID, CHOICE_ID,CHOICE_DESCRIPTION,CORRECT_CHOICE) VALUES (?,?,?,?)';
	public static $OBJECTIVE_CHOICES_UPDATE = 'UPDATE OBJECTIVE_CHOICES SET CHOICE_DESCRIPTION =?, CORRECT_CHOICE = ? WHERE QUESTION_ID = ? AND CHOICE_ID = ?';


	public static $QUESTION_FIND_ALL_QUESTIONS_FOR_INTERVIEW =
		'SELECT Q.INTERVIEW_ID, C.CHOICE_ID FROM QUESTION AS Q LEFT JOIN OBJECTIVE_CHOICES AS C ON Q.QUESTION_ID = C.QUESTION_ID WHERE Q.INTERVIEW_ID = ?';


	public static $QUESTION_FIND_BY_PRIMARY_KEY =
		'SELECT Q.INTERVIEW_ID, Q.STAGE_NO,Q.QUESTION_ID, Q.DESCRIPTION,Q.QUESTION_TYPE, Q.ANSWER_TYPE, Q.ASSESSMENT_CRITERIA, Q.TIME_LIMIT,
		C.CHOICE_ID,C.CHOICE_DESCRIPTION,C.CORRECT_CHOICE
		FROM QUESTION AS Q
		LEFT JOIN OBJECTIVE_CHOICES AS C ON Q.QUESTION_ID = C.QUESTION_ID
		WHERE Q.QUESTION_ID = ?';

	// SELECT Q.INTERVIEW_ID, C.CHOICE_ID FROM QUESTION AS Q LEFT JOIN OBJECTIVE_CHOICES AS C ON Q.QUESTION_ID = C.QUESTION_ID AND Q.INTERVIEW_ID = 5

}